#!/usr/bin/env python3
"""Regenerate the "Interesting Points" list in the viewer's index.html from
points_of_interest.json. Run from the repo root after editing the JSON:

    python3 cli/gen_points_html.py
"""
import html
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
JSON = ROOT / "pages" / "mandelbrot" / "points_of_interest.json"
HTML = ROOT / "pages" / "mandelbrot" / "index.html"

FRACTAL_ID = {"mandelbrot": 0, "julia": 1, "multibrot": 2, "tricorn": 3, "burning_ship": 4}

START = "<!-- POINTS:START (generated by cli/gen_points_html.py) -->"
END = "<!-- POINTS:END -->"


def build_divs(points):
    lines = []
    for p in points:
        fid = FRACTAL_ID[p.get("fractal", "mandelbrot")]
        params = p.get("params", {})
        attrs = [
            f'data-fractal="{fid}"',
            f'data-re="{p["re"]}"',
            f'data-im="{p["im"]}"',
            f'data-zoom="{p["zoom"]}"',
            f'data-maxiter="{p["maxiter"]}"',
            f'data-cycles="{p["cycles"]}"',
        ]
        if "degree" in params:
            attrs.append(f'data-degree="{params["degree"]}"')
        if "julia_re" in params:
            attrs.append(f'data-juliare="{params["julia_re"]}"')
        if "julia_im" in params:
            attrs.append(f'data-juliaim="{params["julia_im"]}"')
        label = html.escape(f'{p["id"]}. {p["name"]}')
        lines.append(f'      <div class="ipoint" {" ".join(attrs)}>{label}</div>')
    return "\n".join(lines)


def main():
    points = json.loads(JSON.read_text())
    block = f"{START}\n{build_divs(points)}\n      {END}"
    text = HTML.read_text()
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if pattern.search(text):
        text = pattern.sub(block, text)
    else:
        # First run: insert the block just before the footnote.
        marker = '      <div id="ipoints-footnote">'
        text = text.replace(marker, block + "\n" + marker, 1)
    HTML.write_text(text)
    print(f"Wrote {len(points)} interesting points into {HTML.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
